groups:
- name: Zero Downtime
  jobs:
  - zero-downtime-deploy
  - test
- name: Canary
  jobs:
  - test
  - deploy-canary
  - uat-canary
- name: A/B
  jobs:
  - deploy-A-and-B
- name: Admin
  jobs:
  - teardown
  - setup

resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/kartiklunkad26/pcf-ers-demo
      branch: master

  - name: deployment-scripts
    type: git
    source:
      uri: https://github.com/kartiklunkad26/pcf-ers-demo
      branch: master

  - name: pcf-ers-demo-releases
    type: github-release
    source:
      user: klunkad-pivotal
      repository: pcf-ers-demo

jobs:
  - name: test
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: test
      file: pcf-ers-demo/concourse/tasks/test.yml

  - name: zero-downtime-deploy
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [test]
    - task: zero-downtime-deploy
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
        APP_NAME: {{APP_NAME}}
      privileged: true
      file: pcf-ers-demo/concourse/tasks/zero-downtime-push.yml

  - name: deploy-A-and-B
    plan:
    - aggregate:
      - get: deployment-scripts
      - get: pcf-ers-demo-releases
        version:
          in:
          tag: v1.0.0-AB
    - task: push
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_DOMAIN: {{PCF_DOMAIN}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
        APP_NAME: {{APP_NAME}}
      file: deployment-scripts/concourse/tasks/ab-push.yml

  - name: deploy-canary
    plan:
    - get: pcf-ers-demo
      passed: [test]
    - task: canary-push
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
        APP_NAME: {{APP_NAME}}
      privileged: true
      file: pcf-ers-demo/concourse/tasks/canary-push.yml

  - name: uat-canary
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [deploy-canary]
    - task: canary-uattest
      file: pcf-ers-demo/concourse/tasks/canary-uattest.yml
      on_success:
        task: scale-canary
        params:
          PCF_TARGET_URL: {{PCF_TARGET_URL}}
          PCF_DOMAIN: {{PCF_DOMAIN}}
          PCF_USERNAME: {{PCF_USERNAME}}
          PCF_PASSWORD: {{PCF_PASSWORD}}
          PCF_ORG: {{PCF_ORG}}
          PCF_SPACE: {{PCF_SPACE}}
          APP_NAME: {{APP_NAME}}
        file: pcf-ers-demo/concourse/tasks/canary-scale.yml

  - name: teardown
    plan:
    - get: pcf-ers-demo
      trigger: false
    - task: teardown
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
        APP_NAME: {{APP_NAME}}
      file: pcf-ers-demo/concourse/tasks/teardown-all.yml
  - name: setup
    plan:
    - get: pcf-ers-demo
      trigger: false
    - task: setup
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
        APP_NAME: {{APP_NAME}}
      file: pcf-ers-demo/concourse/tasks/setup.yml
